import Anthropic from "@anthropic-ai/sdk";

/**
 * The Anthropic path, unchanged in behaviour from before providers existed.
 *
 * Everything here that looks like a micro-optimisation is one, and the README
 * has the measurements: thinking is off because nothing reads it and it bills
 * at output rates, the system prefix is cached on a one-hour TTL because
 * players spend minutes writing a policy, and the two tiers are two different
 * models because the flavour does not need the expensive one.
 */

const MODELS = {
  judge: () => process.env.FP_MODEL || "claude-sonnet-5",
  chat: () => process.env.FP_CHAT_MODEL || "claude-haiku-4-5",
};

let client = null;
const getClient = () => (client ||= new Anthropic());

export function anthropicInfo() {
  return {
    label: "Live AI · Anthropic",
    detail: `Every situation, consequence and voter quote is generated by ${MODELS.judge()}.`,
    model: MODELS.judge(),
    chatModel: MODELS.chat(),
    local: false,
  };
}

export async function completeAnthropic({
  system, messages, tier = "judge", maxTokens = 4096, temperature, cache = false,
}) {
  const model = MODELS[tier] ? MODELS[tier]() : MODELS.judge();
  const resp = await getClient().messages.create({
    model,
    max_tokens: maxTokens,
    ...(temperature != null ? { temperature } : {}),
    // Caching has a 4,096-token minimum; below it cache_control is inert and
    // billed in full, so it is only asked for where the prefix earns it.
    system: cache
      ? [{ type: "text", text: system, cache_control: { type: "ephemeral", ttl: "1h" } }]
      : system,
    messages,
  });

  const text = (resp.content || [])
    .filter((b) => b.type === "text").map((b) => b.text).join("");
  return {
    text, model,
    usage: {
      in: resp.usage?.input_tokens ?? 0,
      out: resp.usage?.output_tokens ?? 0,
      cached: resp.usage?.cache_read_input_tokens ?? 0,
    },
  };
}
